### ISSUE TITLE
Add .devcontainer for the rocket speed development

### ISSUE THREAD

**Issue by urandon** [langprogramming-AsmX/AsmX#3]
Our AsmX developer community grows fast and in a dedicated manner.
We require the most reliable and efficient development infrastructure to bring our community to the moon as soon as possible!

Github Codespaces Development Container Images and VS Code Remote are the most fascinating technologies for leading the project to a shared community success.

See more at the following links:
- https://code.visualstudio.com/docs/devcontainers/containers
- https://github.com/devcontainers
- https://hub.docker.com/_/microsoft-vscode-devcontainers

**Comment by E5war5IT** [comment]
Thanks!

**Comment by E5war5IT** [comment]
Check Please. Dir `docker`
