### ISSUE TITLE
Source code not in src

### ISSUE THREAD

**Issue by DarkHole1** [langprogramming-AsmX/AsmX#9]
Every source code file should be in appropriate place in folders. And EVERY source code file (`.js`) should be under src folder.

**Comment by DarkHole1** [comment]
FYI, I won't check your code again, at least until you fix this and #7.

**Comment by DarkHole1** [comment]
Note: Still not solved, just marked as completed

**Comment by E5war5IT** [comment]
package.json is there, what else is needed?

**Comment by DarkHole1** [comment]
> Source code not in src

> Every source code file should be in appropriate place in folders. And EVERY source code file (.js) should be under src folder.

> what else is needed

**Comment by E5war5IT** [comment]
Not in all projects like the llvm example

**Comment by DarkHole1** [comment]
Llvm? No, it's not llvm. Every popular js project keep his files in src folder. Or maybe in lib. It's just common sense for placing all source files in separate folder, to get files separated from non-code.
